// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsPT9i0Yr1vbbfAFb-91rXq5nyqq6aQgk',
    appId: '1:521340901705:web:a28087263c955622c6e298',
    messagingSenderId: '521340901705',
    projectId: 'kawan-touring',
    authDomain: 'kawan-touring.firebaseapp.com',
    storageBucket: 'kawan-touring.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXXTOXDsrWP6Q1z8zUO1ux_Tzb5BlM-ik',
    appId: '1:521340901705:android:f7160827243eacdbc6e298',
    messagingSenderId: '521340901705',
    projectId: 'kawan-touring',
    storageBucket: 'kawan-touring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTw3k882ZVJW_ZOqykqcByyHtwuA_LD9s',
    appId: '1:521340901705:ios:6945984a4fcb472ec6e298',
    messagingSenderId: '521340901705',
    projectId: 'kawan-touring',
    storageBucket: 'kawan-touring.appspot.com',
    androidClientId: '521340901705-ihepl5fcrghpqnke1vljp4rnm7tu5ucc.apps.googleusercontent.com',
    iosClientId: '521340901705-olph9prhht366e3rtopj4lgfhoo4fkb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kawanTouring',
  );
}
